---
Pools:
  - name: web_pool_1
    monitors:
      - /Common/tcp
      - /Common/http
    members:
      - host: 10.33.10.10
        port: 80
        state: enabled
      - host: 10.33.10.11
        port: 80
        state: enabled
    state: present
  - name: web_pool_2
    monitors:
      - /Common/tcp
    members:
      - host: 1.1.1.1
        port: 80
        state: enabled
      - host: 1.1.1.2
        port: 80
        state: enabled

Virtual_Servers:
  - name: web_vip
    all_profiles:
      - http
    destination: 10.0.10.106
    port: 80
    pool: web_pool_2
    snat: automap
  - name: web_vip_2
    all_profiles:
      - http
    destination: 10.0.10.107
    port: 80
    pool: web_pool_1
    snat: automap
