---
provider:
  server: "{{ ansible_host }}"
  user: "{{ (lookup('aws_secret', inventory_hostname, region='us-west-1') | from_json).get('username') }}"
  password: "{{ (lookup('aws_secret', inventory_hostname, region='us-west-1') | from_json).get('password') }}"
  validate_certs: false

HTTP_Health_Monitors:
  - name: test_http_monitor
    send: "/"
    receive: "It Works!"
  - name: test_http_monitor2
    send: "/"
    receive: "200"

iRules:
  - name: test_irule_1
    content: "{{ lookup('file', playbook_dir + '/irules/test_irule_1.tcl') }}"
    module: ltm
  - name: test_irule_2
    content: "{{ lookup('file', playbook_dir + '/irules/test_irule_2.tcl') }}"
    module: ltm
